export * from './auth.interface';
export * from './error.interface';
export * from './hijo.interface';
export * from './licencia.interface';
export * from './notification.interface';
export * from './padre.interface';
export * from './reunion.interface';
export * from './user.interface';
export * from './libreta.interface';
